#!/usr/bin/env bash
# Local ClickHouse 24.10 rig for developing cobserve without touching the fleet.
#
#   ch-a   127.0.0.1:8123   native 9000   cluster ch_cluster, shard 1, replica paymon_ch1
#   ch-b   127.0.0.1:8124   native 9002   cluster ch_cluster, shard 1, replica paymon_ch2
#   ch-keeper                     9181   so system.replicas has rows and lag is a real number
#
#   ./dev/local-rig.sh up      start everything, render users, seed the testing database
#   ./dev/local-rig.sh down    stop and remove the containers
#   ./dev/local-rig.sh load    start a few long-running queries so system.processes has rows
#   ./dev/local-rig.sh env     print the env vars for running the app
#   ./dev/local-rig.sh credentials
#                              write dev/local/credentials.yaml — a login per node — for
#                              `cobserve --credential dev/local/credentials.yaml`
#   ./dev/local-rig.sh status  what each node reports (version, cluster rows, lag)
#
# Passwords are generated per run and live in dev/local/.env (gitignored). The fleet is
# never contacted by anything in here.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOCAL="$ROOT/dev/local"
CONFIGS="$LOCAL/configs"
STATE="$LOCAL/.env"
NET="paymon"
CH_IMAGE="clickhouse/clickhouse-server:24.10"
KEEPER_IMAGE="clickhouse/clickhouse-keeper:24.10"
VERSION="24.10"

mkdir -p "$LOCAL/rendered"

render_users() {
  local node="$1"
  python3 - "$CONFIGS/users.xml" "$LOCAL/rendered/users-$node.xml" "$node" <<'PY'
import os, sys
src, dst, node = sys.argv[1], sys.argv[2], sys.argv[3]
state = os.path.join(os.path.dirname(os.path.dirname(dst)), ".env")
vals = {}
for line in open(state):
    line = line.strip()
    if line and not line.startswith("#") and "=" in line:
        k, v = line.split("=", 1)
        vals[k.strip()] = v.strip()
html = open(src).read()
for key, placeholder in (
    ("CH_MONITOR_PASSWORD", "__MONITOR_PASSWORD__"),
    ("CH_REDASH_PASSWORD", "__REDASH_PASSWORD__"),
    ("CH_RIG_PASSWORD", "__RIG_PASSWORD__"),
):
    if key not in vals:
        raise SystemExit(f"{state} has no {key}")
    html = html.replace(placeholder, vals[key])
# The node's own login: monitor_a exists only on ch-a, monitor_b only on ch-b.
own = f"CH_MONITOR_{node.upper()}_PASSWORD"
if own not in vals:
    raise SystemExit(f"{state} has no {own}")
html = html.replace("__NODE_USER__", f"monitor_{node}").replace("__NODE_PASSWORD__", vals[own])
open(dst, "w").write(html)
PY
}

wait_http() {
  local url="$1" tries="${2:-60}"
  for _ in $(seq "$tries"); do
    if curl -fsS --max-time 2 "$url/ping" >/dev/null 2>&1; then return 0; fi
    sleep 1
  done
  echo "timed out waiting for $url" >&2
  return 1
}

ch_query() {
  local url="$1"; shift
  local user="$1"; shift
  local pass="$1"; shift
  curl -fsS --max-time 30 -H "X-ClickHouse-User: $user" -H "X-ClickHouse-Key: $pass" \
    --data-binary "$*" "$url/"
}

cmd_up() {
  if [[ ! -f "$STATE" ]]; then
    # The umask is for this file only, so it lives in a subshell: left on for the rest of
    # the function it makes the rendered configs 0600, and on a Linux host (no Docker
    # Desktop file sharing to paper over it) the clickhouse user in the container cannot
    # read them — "Access to file denied" and the node never starts.
    (
      umask 077
      {
        echo "# generated by dev/local-rig.sh — local dev credentials, never commit"
        echo "CH_MONITOR_PASSWORD=$(openssl rand -hex 12)"
        echo "CH_REDASH_PASSWORD=$(openssl rand -hex 12)"
        echo "CH_RIG_PASSWORD=$(openssl rand -hex 12)"
      } >"$STATE"
    )
    echo "wrote $STATE"
  fi
  # A rig from before the per-node logins gets their passwords added.
  for key in CH_MONITOR_A_PASSWORD CH_MONITOR_B_PASSWORD; do
    grep -q "^$key=" "$STATE" || (umask 077 && echo "$key=$(openssl rand -hex 12)" >>"$STATE")
  done
  # shellcheck disable=SC1090
  source "$STATE"
  render_users a
  render_users b

  docker network inspect "$NET" >/dev/null 2>&1 || docker network create "$NET" >/dev/null
  # Redash lives on redash-dev; attaching the nodes there too lets its data source reach
  # them by container name.
  docker network inspect redash-dev >/dev/null 2>&1 &&
    docker network connect "$NET" rd-server >/dev/null 2>&1 || true

  docker rm -f ch-keeper ch-a ch-b >/dev/null 2>&1 || true

  docker run -d --name ch-keeper --network "$NET" --network-alias ch-keeper \
    -v "$CONFIGS/keeper.xml:/etc/clickhouse-keeper/keeper_config.xml:ro" \
    "$KEEPER_IMAGE" >/dev/null

  for node in a b; do
    local http=8123 native=9000
    [[ "$node" == b ]] && { http=8124; native=9002; }
    python3 - "$CONFIGS/cluster.xml" "$LOCAL/rendered/cluster-$node.xml" "$node" <<'PY'
import sys
src, dst, node = sys.argv[1], sys.argv[2], sys.argv[3]
html = open(src).read()
html = html.replace("__REPLICA_NAME__", "paymon_ch1" if node == "a" else "paymon_ch2")
open(dst, "w").write(html)
PY
    # --memory / --cpus matter: without a cgroup limit Docker Desktop reports
    # CGroupMemoryTotal = 0 and no CGroup*TimeNormalized family at all, so the rig could
    # only ever show the unknown-denominator path from DESIGN.md §5.
    docker run -d --name "ch-$node" --network "$NET" --network-alias "ch-$node" \
      --memory=2g --cpus=2 \
      -p "127.0.0.1:$http:8123" -p "127.0.0.1:$native:9000" \
      -v "$LOCAL/rendered/cluster-$node.xml:/etc/clickhouse-server/config.d/cluster.xml:ro" \
      -v "$LOCAL/rendered/users-$node.xml:/etc/clickhouse-server/users.d/users.xml:ro" \
      -e CLICKHOUSE_DB=testing \
      "$CH_IMAGE" >/dev/null
  done

  wait_http "http://127.0.0.1:8123"
  wait_http "http://127.0.0.1:8124"

  seed
  echo
  echo "ch-a   http://127.0.0.1:8123"
  echo "ch-b   http://127.0.0.1:8124"
  echo "env   source $STATE && ./dev/local-rig.sh env"
}

seed() {
  # shellcheck disable=SC1090
  source "$STATE"
  local a="http://127.0.0.1:8123" b="http://127.0.0.1:8124"
  local u="$CH_RIG_PASSWORD"
  # One statement per request: the HTTP interface rejects multi-statements unless
  # multiquery=1, and splitting them keeps the error messages readable.
  for url in "$a" "$b"; do
    ch_query "$url" rig "$u" "CREATE DATABASE IF NOT EXISTS testing" >/dev/null
    ch_query "$url" rig "$u" "
      CREATE TABLE IF NOT EXISTS testing.events (
        event_time DateTime, user String, amount UInt64, currency LowCardinality(String)
      ) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/events', '{replica}')
      ORDER BY (event_time, user)" >/dev/null
    ch_query "$url" rig "$u" "
      INSERT INTO testing.events SELECT
        now() - number * 60, concat('user', number % 50), number * 13, 'EUR'
      FROM numbers(200000) WHERE number % 7 != 0" >/dev/null
  done
  echo "seeded testing.events on both nodes"
}

cmd_load() {
  # shellcheck disable=SC1090
  source "$STATE"
  local u="$CH_MONITOR_PASSWORD"
  for url in http://127.0.0.1:8123 http://127.0.0.1:8124; do
    for i in 1 2 3; do
      curl -sS --max-time 1 -H "X-ClickHouse-User: monitor" -H "X-ClickHouse-Key: $u" \
        --data-binary "SELECT count(), sum(amount), uniq(user) FROM testing.events SETTINGS max_execution_time=600, max_threads=1" \
        "$url/?send_progress_in_http_headers=1" >/dev/null 2>&1 &
    done
    # One runaway-shaped query, so the >= 30s severity path is exercised.
    curl -sS --max-time 1 -H "X-ClickHouse-User: monitor" -H "X-ClickHouse-Key: $u" \
      --data-binary "SELECT count() FROM testing.events ARRAY JOIN range(2000) AS x SETTINGS max_execution_time=600, max_threads=1" \
      "$url/?send_progress_in_http_headers=1" >/dev/null 2>&1 &
  done
  echo "started 8 queries; they are killed when the client disconnects or after 600s"
}

cmd_env() {
  # shellcheck disable=SC1090
  source "$STATE"
  cat <<EOF
export FAKE=
export CH_SEED_URLS=http://127.0.0.1:8123,http://127.0.0.1:8124
export CH_CLUSTER=ch_cluster
export CH_USER=monitor
export CH_PASSWORD=$CH_MONITOR_PASSWORD
export CH_HTTP_PORT=8123
export REDASH_URL=http://localhost:5001
export REDASH_ADMIN_API_KEY=\$(cat "$LOCAL/redash_api_key" 2>/dev/null || true)
export REDIS_URL=redis://127.0.0.1:6379
export POLL_MS=2000
EOF
}

cmd_credentials() {
  # shellcheck disable=SC1090
  source "$STATE"
  local file="$LOCAL/credentials.yaml"
  (
    umask 077
    cat >"$file" <<EOF
# generated by dev/local-rig.sh credentials — local dev logins, never commit
# A login per server, the way the fleet can have them: monitor_a exists only on ch-a and
# monitor_b only on ch-b, so a login sent to the wrong node is refused.
clickhouse:
  cluster: ch_cluster
  servers:
    - url: http://127.0.0.1:8123
      user: monitor_a
      password: "$CH_MONITOR_A_PASSWORD"
    - url: http://127.0.0.1:8124
      user: monitor_b
      password: "$CH_MONITOR_B_PASSWORD"
EOF
  )
  chmod 600 "$file"
  echo "wrote $file"
  echo "run   cargo run --release -- --credential $file"
}

cmd_status() {
  # shellcheck disable=SC1090
  source "$STATE"
  for pair in "ch-a http://127.0.0.1:8123" "ch-b http://127.0.0.1:8124"; do
    set -- $pair
    echo "== $1 $2"
    ch_query "$2" monitor "$CH_MONITOR_PASSWORD" "
      SELECT version() AS version, uptime() AS uptime_s,
             (SELECT value FROM system.asynchronous_metrics WHERE metric='OSMemoryTotal' LIMIT 1) AS os_mem_total,
             (SELECT value FROM system.asynchronous_metrics WHERE metric='MemoryResident' LIMIT 1) AS resident,
             (SELECT max(absolute_delay) FROM system.replicas) AS lag_s,
             (SELECT count() FROM system.parts WHERE active) AS parts,
             (SELECT toUInt64OrZero(value) FROM system.settings WHERE name='max_memory_usage') AS max_mem
      FORMAT PrettyCompact
    "
  done
  echo "== system.clusters (from ch-a)"
  ch_query http://127.0.0.1:8123 monitor "$CH_MONITOR_PASSWORD" \
    "SELECT cluster, shard_num, replica_num, host_name, host_address, port FROM system.clusters FORMAT PrettyCompact"
}

case "${1:-up}" in
up) cmd_up ;;
down)
  docker rm -f ch-keeper ch-a ch-b >/dev/null 2>&1 || true
  echo "stopped"
  ;;
load) cmd_load ;;
status) cmd_status ;;
env) cmd_env ;;
credentials) cmd_credentials ;;
*)
  echo "usage: $0 {up|down|load|env|credentials|status}" >&2
  exit 2
  ;;
esac